List<Map<String, dynamic>> petPosts = [
    {
      'image': 'model/assets/kremscottish.jpeg',
      'title': 'Minik',
      'age': '1',
      'gender': 'Erkek',
      'breed': 'Scottish Fold',
      'color': 'Krem',
      'description': 'Tatlı ve oyuncu bir kedi arıyoruz. İlgilenenler bize ulaşabilirler.',
    },
    {
      'image': 'model/assets/golden.jpeg',
      'title': 'Boncuk',
      'age': '2',
      'gender': 'Dişi',
      'breed': 'Golden Retriever',
      'color': 'Sarı',
      'description': 'Enerjik ve sevecen bir köpek sahiplenmek istiyoruz. İlgilenenler için iletişime geçin.',
    },
    {
      'image': 'model/assets/muhabbetkusu.jpeg',
      'title': 'Maviş',
      'age': '3',
      'gender': 'Dişi',
      'breed': 'Muhabbet Kuşu',
      'color': 'Mavi',
      'description': 'Konuşkan ve eğlenceli bir muhabbet kuşu arıyoruz. İlgilenenler bize ulaşabilirler.',
    },
    {
      'image': 'model/assets/hollandlop.jpeg',
      'title': 'Lapino',
      'age': '1',
      'gender': 'Erkek',
      'breed': 'Holland Lop',
      'color': 'Kahverengi',
      'description': 'Sevimli ve uysal bir tavşan arıyoruz. İlgilenenler için detaylar aşağıda yer alıyor.',
    },
    {
      'image': 'model/assets/suriye.jpeg',
      'title': 'Pamuk',
      'age': '1',
      'gender': 'Dişi',
      'breed': 'Suriye Hamster',
      'color': 'Beyaz',
      'description': 'Küçük ve sevimli bir hamster arıyoruz. İlgilenenler bize ulaşabilirler.',
    },
    {
      'image': 'model/assets/akvaryum.jpeg',
      'title': 'Akvaryum Balığı',
      'age': '2',
      'gender': 'Dişi',
      'breed': 'Ciklet',
      'color': 'Mavi',
      'description': 'Renkli ve canlı bir akvaryum balığı sahiplenmek istiyoruz. İlgilenenler için detaylar aşağıda yer alıyor.',
    },
    {
      'image': 'model/assets/sarıkanarya.jpeg',
      'title': 'Kanarya',
      'age': '1',
      'gender': 'Erkek',
      'breed': 'Kanarya',
      'color': 'Sarı',
      'description': 'Şarkı söyleyen ve hareketli bir kanarya arıyoruz. İlgilenenler bize ulaşabilirler.',
    },
  ];