// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ-x0-rAVyy3eWsfHvy9qmcArsZ9AjDag',
    appId: '1:448536356167:web:48f28c5935ca829a6d1862',
    messagingSenderId: '448536356167',
    projectId: 'bootcamp-760bf',
    authDomain: 'bootcamp-760bf.firebaseapp.com',
    storageBucket: 'bootcamp-760bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgS4ml41R20P3PQYfI5VMHXXUCsYgjDvk',
    appId: '1:448536356167:android:48c09ac161e1aa496d1862',
    messagingSenderId: '448536356167',
    projectId: 'bootcamp-760bf',
    storageBucket: 'bootcamp-760bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB10Rcz_ResnF_KMBE6PMUqMm74_6T1EHY',
    appId: '1:448536356167:ios:beb2b0a40f487b046d1862',
    messagingSenderId: '448536356167',
    projectId: 'bootcamp-760bf',
    storageBucket: 'bootcamp-760bf.appspot.com',
    iosClientId: '448536356167-k0cmmqeioppdacpo4kbd53gd8hdf2b6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.bootcampTeam83Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB10Rcz_ResnF_KMBE6PMUqMm74_6T1EHY',
    appId: '1:448536356167:ios:beb2b0a40f487b046d1862',
    messagingSenderId: '448536356167',
    projectId: 'bootcamp-760bf',
    storageBucket: 'bootcamp-760bf.appspot.com',
    iosClientId: '448536356167-k0cmmqeioppdacpo4kbd53gd8hdf2b6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.bootcampTeam83Flutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ-x0-rAVyy3eWsfHvy9qmcArsZ9AjDag',
    appId: '1:448536356167:web:5f8309d4391ce0466d1862',
    messagingSenderId: '448536356167',
    projectId: 'bootcamp-760bf',
    authDomain: 'bootcamp-760bf.firebaseapp.com',
    storageBucket: 'bootcamp-760bf.appspot.com',
  );
}
