  // Kayıt Oluşturma (Ethem Sabah)
  // Şifre Güncelleme (Ethem Sabah)
  // Giriş Yapma (Muhammet İkbal Sağdıç)
  // Profil Oluşturma (Muhammet İkbal Sağdıç)
  // Takip Et (Zehra Gültekin)
  // Beğeni Ekleme (Zehra Gültekin)
  // Biyografi - Bağlantı (Melahat Başar)
  // Raporlama/Engelleme (Melahat Başar)
  // Arama (İclal Çetin)
  // Filtreleme (Arama Çubuğu) (İclal Çetin)
  // Gönderi Listeleme (Muhammet İkbal Sağdıç)
// Gönderi Ekleme (Muhammet İkbal Sağdıç)
  // Gönderi Silme (Muhammet İkbal Sağdıç)
// Gönderi Güncelleme (Muhammet İkbal Sağdıç)
  // Yorum Listeleme (Ethem Sabah)
// Yorum Ekleme (Ethem Sabah)
  // Yorum Silme (Ethem Sabah)
  // Yorum Güncelleme (Ethem Sabah)
  // Sahiplendirme Formu Listeleme (İclal Çetin)
  // Sahiplendirme Formuna Ekleme (İclal Çetin)
  // Sahiplendirme Formundan Silme (İclal Çetin)
  // Sahiplendirme Formunda Güncelleme (İclal Çetin)
  // Eşleştirme Formu Listeleme (Zehra Gültekin)
// Eşleştirme Formuna Ekleme (Zehra Gültekin)
// Eşleştirme Formundan Silme (Zehra Gültekin)
// Eşleştirme Formunda Güncelleme (Zehra Gültekin)
  // Etkinlik Formu Listeleme (Melahat Başar)
  // Etkinlik Formuna Ekleme (Melahat Başar)
  // Etkinlik Formundan Silme (Melahat Başar)
  // Etkinlik Formunda Güncelleme (Melahat Başar)